name:           yatima
version:        0.1.0.0
homepage:       "moonad/yatima"
author:         "Gabriel Barreto, John C. Burnham"
maintainer:     john@yatima.io
copyright:      2020 Sunshine Cybernetics

extra-source-files:
- README.md
- LICENSE

description:
  Please see the README on GitHub at <https://github.com/moonad/yatima#readme>

library:
  source-dirs: src
  exposed-modules:
    - Yatima.CID
    - Yatima.Core
    - Yatima.Core.Wasm
    - Yatima.Core.Ctx
    - Yatima.Core.Hoas
    - Yatima.DagAST
    - Yatima.DagJSON
    - Yatima.Import
    - Yatima.IR
    - Yatima.Compiler.Scheme
    - Yatima.IPFS
    - Yatima.IPLD
    - Yatima.Literal
    - Yatima.Package
    - Yatima.Parse
    - Yatima.Parse.Integer
    - Yatima.PrimOp
    - Yatima.Print
    - Yatima.QuasiQuoter
    - Yatima.Term
    - Yatima.Uses
    - Yatima

  dependencies:
    - base >= 4.7 && < 5
    - containers
    - text
    - mtl
    - megaparsec
    - path
    - path-io
    - exceptions
    - file-embed
    - serialise
    - bytestring
    - base16
    - multibase
    - cryptonite
    - multihash-cryptonite
    - ipld-cid
    - cborg
    - vector
    - scientific
    - unordered-containers
    - unsafeperformst
    - servant
    - servant-client
    - http-client
    - http-client-tls
    - http-types
    - aeson
    - ipfs-api
    - numeric-extras
    - ieee754
    - cereal
    - array
    - template-haskell
    - syb

  default-extensions:
    - OverloadedStrings
    - GADTSyntax
    - StandaloneDeriving
    - MultiWayIf
    - TupleSections

executables:
  #yatima:
  #  main: Main.hs
  #  source-dirs: yide

  yide:
    main: Main.hs
    source-dirs: yide
    dependencies:
      - base >= 4.7 && < 5
      - containers
      - text
      - yatima
      - mtl
      - megaparsec
      - haskeline
      - process
      - path
      - path-io
      # - serialise
      # - bytestring
      # - base16-bytestring
      # - multibase
      # - cryptonite
      # - multihash-cryptonite
      # - ipld-cid
      # - unsafeperformst
      # - aeson
      # - servant
      # - servant-client
      # - http-client
      # - cborg
      # - ipfs-api
    default-extensions:
      - OverloadedStrings
      - GADTSyntax
      - StandaloneDeriving
      - MultiWayIf
      - TypeApplications
      - ScopedTypeVariables

tests:
  spec:
    main:                Spec.hs
    source-dirs:
      - test
    #ghc-options:
    #- -threaded
    #- -rtsopts
    #- -with-rtsopts=-N
    dependencies:
      - base
      - yatima
      - megaparsec
      - containers
      - transformers
      - mtl
      - text
      - vector
      - unsafeperformst
      - utf8-string
      - hspec
      - QuickCheck
      - quickcheck-instances
      - raw-strings-qq
      - bytestring
      - multibase
      - ipld-cid
      - serialise
      - cborg
      - cryptonite
      - multihash-cryptonite
      - base16-bytestring
    default-extensions:
      - OverloadedStrings
      - GADTSyntax
      - StandaloneDeriving
      - MultiWayIf
      - TypeApplications
      - ScopedTypeVariables
    other-modules:
      - Spec.IPLD
      - Spec.Parse
      - Spec.Print
      - Spec.Instances

