name:           yatima
version:        0.1.0.0
homepage:       "moonad/yatima"
author:         "Gabriel Barreto, John C. Burnham, Victor Maia"
maintainer:     john@sunshinecybernetics.com
copyright:      2020 Sunshine Cybernetics

extra-source-files:
- README.md
- LICENSE

description:
  Please see the README on GitHub at <https://github.com/moonad/yatima#readme>

library:
  source-dirs: src
  exposed-modules:
    - Language.Yatima.Term
    - Language.Yatima.Defs
    - Language.Yatima.CID
    - Language.Yatima.Uses
    - Language.Yatima.Print
    - Language.Yatima.Parse
    - Language.Yatima.HOAS
    - Language.Yatima.IPFS

  dependencies:
    - base >= 4.7 && < 5
    - containers
    - text
    - mtl
    - megaparsec
    - serialise
    - bytestring
    - base16-bytestring
    - multibase
    - cryptonite
    - multihash-cryptonite
    - ipld-cid
    - unsafeperformst
    - aeson
    - servant
    - servant-client
    - http-client
    - cborg
    - ipfs-api
    - directory


  default-extensions:
    - OverloadedStrings
    - GADTSyntax
    - StandaloneDeriving
    - MultiWayIf
    - TupleSections

executables:
  yide:
    main: Main.hs
    source-dirs: yide
    dependencies:
      - base >= 4.7 && < 5
      - containers
      - text
      - yatima
      - mtl
      - megaparsec
      - haskeline
      - process
      # - serialise
      # - bytestring
      # - base16-bytestring
      # - multibase
      # - cryptonite
      # - multihash-cryptonite
      # - ipld-cid
      # - unsafeperformst
      # - aeson
      # - servant
      # - servant-client
      # - http-client
      # - cborg
      # - ipfs-api
    default-extensions:
      - OverloadedStrings
      - GADTSyntax
      - StandaloneDeriving
      - MultiWayIf
      - TypeApplications
      - ScopedTypeVariables

